runtime: python37
entrypoint: gunicorn -b :$PORT main:app --timeout 600
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

service: "service_name"

handlers:
- url: your_app_url
  script: auto
  #secure: always